<a href="https://colab.research.google.com/github/Uthmanic/DSN-AI-Bootcamp-2020/blob/master/DSN_bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
%matplotlib inline

In [2]:
train = pd.read_csv('https://raw.githubusercontent.com/Uthmanic/DSN-AI-Bootcamp-2020/master/Train.csv')
test = pd.read_csv('https://raw.githubusercontent.com/Uthmanic/DSN-AI-Bootcamp-2020/master/Test.csv')
train_copy = train.copy()
test_copy = test.copy()

In [3]:
#train.info()

In [4]:
#train_copy.isnull().sum()

In [5]:
#test_copy.isnull().sum()

In [6]:
test_copy.head()

    Applicant_ID  form_field1  ...  form_field49  form_field50
0  Apcnt_1000032       3236.0  ...      0.000000      0.011221
1  Apcnt_1000048       3284.0  ...      0.504974      0.043525
2  Apcnt_1000052          NaN  ...      0.000000           NaN
3  Apcnt_1000076       3232.0  ...      0.788809      0.104029
4  Apcnt_1000080       3466.0  ...      1.637733      0.163124

[5 rows x 51 columns]

In [7]:
train_copy.head()

    Applicant_ID  form_field1  ...  form_field50  default_status
0  Apcnt_1000000       3436.0  ...      0.044335              no
1  Apcnt_1000004       3456.0  ...      0.322436              no
2  Apcnt_1000008       3276.0  ...      0.011640             yes
3  Apcnt_1000012       3372.0  ...      0.082729              no
4  Apcnt_1000016       3370.0  ...      0.045630              no

[5 rows x 52 columns]

In [8]:
train_copy = train_copy.fillna(-1)
test_copy = test_copy.fillna(-1)

In [9]:
#train_copy.isnull().sum()

In [10]:
#test_copy.isnull().sum()

In [11]:
from sklearn.preprocessing import LabelEncoder
 
train_copy["form_field47"] = LabelEncoder().fit_transform(train_copy["form_field47"])
train_copy["default_status"] = LabelEncoder().fit_transform(train_copy["default_status"])
test_copy["form_field47"] = LabelEncoder().fit_transform(test_copy["form_field47"])

In [12]:
train_copy.head()

    Applicant_ID  form_field1  ...  form_field50  default_status
0  Apcnt_1000000       3436.0  ...      0.044335               0
1  Apcnt_1000004       3456.0  ...      0.322436               0
2  Apcnt_1000008       3276.0  ...      0.011640               1
3  Apcnt_1000012       3372.0  ...      0.082729               0
4  Apcnt_1000016       3370.0  ...      0.045630               0

[5 rows x 52 columns]

In [13]:
#model feature and target
X = train_copy.drop(["Applicant_ID", "default_status","form_field17"], axis =1)
y = train_copy["default_status"]
 
test_data = test_copy.drop(["Applicant_ID","form_field17"], axis = 1)

In [14]:
import imblearn
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=101)
X_balanced, y_balanced = smote.fit_sample(X, train_copy["default_status"])

/usr/local/lib/python3.6/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)

In [15]:
y_balanced = pd.Series(y_balanced)
X_balanced = pd.DataFrame(X_balanced)

In [16]:
X_balanced.columns = ['form_field1', 'form_field2', 'form_field3', 'form_field4',
                      'form_field5', 'form_field6', 'form_field7', 'form_field8',
                      'form_field9', 'form_field10', 'form_field11', 'form_field12',
                      'form_field13', 'form_field14', 'form_field15', 'form_field16',
                      'form_field18', 'form_field19', 'form_field20', 'form_field21',
                      'form_field22', 'form_field23', 'form_field24', 'form_field25',
                      'form_field26', 'form_field27', 'form_field28', 'form_field29',
                      'form_field30', 'form_field31', 'form_field32', 'form_field33',
                      'form_field34', 'form_field35', 'form_field36', 'form_field37',
                      'form_field38', 'form_field39', 'form_field40', 'form_field41',
                      'form_field42', 'form_field43', 'form_field44', 'form_field45',
                      'form_field46', 'form_field47', 'form_field48', 'form_field49',
                      'form_field50']

In [17]:
from sklearn.model_selection import KFold, train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_balanced, y_balanced, test_size = 0.4, random_state = 101)

In [18]:
!pip install catboost

Collecting catboost
  Downloading https://files.pythonhosted.org/packages/90/86/c3dcb600b4f9e7584ed90ea9d30a717fb5c0111574675f442c3e7bc19535/catboost-0.24.1-cp36-none-manylinux1_x86_64.whl (66.1MB)
     |████████████████████████████████| 66.1MB 58kB/s
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (1.1.2)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from catboost) (1.15.0)
Requirement already satisfied: numpy>=1.16.0 in /usr/local/lib/python3.6/dist-packages (from catboost) (1.18.5)
Requirement already satisfied: graphviz in /usr/local/lib/python3.6/dist-packages (from catboost) (0.10.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.6/dist-packages (from catboost) (3.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.6/dist-packages (from catboost) (1.4.1)
Requirement already satisfied: plotly in /usr/local/lib/python3.6/dist-packages (from catboost) (4.4.1)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.0->catboost) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas>=0.24.0->catboost) (2018.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.6/dist-packages (from matplotlib->catboost) (2.4.7)
Requirement already satisfied: retrying>=1.3.3 in /usr/local/lib/python3.6/dist-packages (from plotly->catboost) (1.3.3)
Installing collected packages: catboost
Successfully installed catboost-0.24.1

In [19]:
from sklearn.metrics import roc_auc_score
from catboost import CatBoostClassifier
from sklearn.model_selection import StratifiedKFold
from lightgbm import LGBMClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import VotingClassifier, StackingClassifier
 
gbc = GradientBoostingClassifier(verbose=100, random_state=101)
etc = ExtraTreesClassifier(verbose=100, random_state=101)
lgbm = LGBMClassifier(random_state=101,verbose=100)
catb = CatBoostClassifier(n_estimators=1000,eval_metric='AUC',max_depth=4,learning_rate=0.1,od_wait=50, reg_lambda=3,
                          bootstrap_type='Bayesian')

In [40]:
# instantiating a VotingClassifier and a StackingClassifier 
 
#vc = VotingClassifier(estimators=[("CatBoost", catb), ("lgbm", lgbm),("gradient boosting",gbc)]) 
 
stack = StackingClassifier(estimators=[("CatBoost", catb), ("lgbm", lgbm),("gradient boosting",gbc)],
                          final_estimator=catb, passthrough=True, cv=17)

vc.fit(X_train, y_train)
print("Model name: VotingClassifier") 
print("Model score:", roc_auc_score(y_test, vc.predict_proba(X_test)))

In [41]:
%%capture
stack.fit(X_train, y_train)
predicto = stack.predict_proba(X_test)[:,1]

In [42]:
roc_auc_score(y_test,predicto)

0.9449397372230534

In [43]:
test_stack = stack.predict_proba(test_data)[:,1]

In [48]:
pd.DataFrame({"Applicant_ID": test_copy["Applicant_ID"], "default_status": test_stack}).to_csv("53_submission.csv", index = False)

In [50]:
from google.colab import files
files.download('53_submission.csv')